spring.application.name=order-service

server.port=8031
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8030/eureka

resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize: 10
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls: 5
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState: 3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled: true
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize: 10
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState: 5s
resilience4j.circuitbreaker.configs.default.failureRateThreshold: 50